
version: "3.8"

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: dokploy
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: dokploy
    volumes:
      - dokploy-postgres-database:/var/lib/postgresql/data
    networks:
      dokploy-network:
        aliases:
          - dokploy-postgres
    deploy:
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: any

  redis:
    image: redis:7
    volumes:
      - redis-data-volume:/data
    networks:
      dokploy-network:
        aliases:
          - dokploy-redis
    deploy:
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: any

  dokploy:
    image: ${DOKPLOY_IMAGE}
    environment:
      ADVERTISE_ADDR: ${ADVERTISE_ADDR}
    networks:
      dokploy-network:
        aliases:
          - dokploy-app
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DATA_DIR}:/etc/dokploy
      - dokploy-docker-config:/root/.docker
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      update_config:
        parallelism: 1
        order: stop-first
      restart_policy:
        condition: any

networks:
  dokploy-network:
    name: dokploy-network
    driver: overlay
    attachable: true

volumes:
  dokploy-postgres-database:
  redis-data-volume:
  dokploy-docker-config:
